#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

if [ -z "$ZSH" ]; then
    echo "The ZSH variable is not set. Exiting."
    exit 1
fi

# cd dotfiles root
pushd "$ZSH" >/dev/null

# find the installers and run them iteratively
find . -name install.sh -exec {} \;

popd >/dev/null
